Oops. didn't get freetype quite right.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -8165,6 +8165,70 @@ if test "${with_freetype_bytecode+set}" = set; then
 
     gww_hasbytecode="$withval"
 
+echo "$as_me:$LINENO: checking for FT_New_Memory_Face in -lfreetype" >&5
+echo $ECHO_N "checking for FT_New_Memory_Face in -lfreetype... $ECHO_C" >&6
+if test "${ac_cv_lib_freetype_FT_New_Memory_Face+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_check_lib_save_LIBS=$LIBS
+LIBS="-lfreetype  $LIBS"
+cat >conftest.$ac_ext <<_ACEOF
+#line $LINENO "configure"
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+/* Override any gcc2 internal prototype to avoid an error.  */
+#ifdef __cplusplus
+extern "C"
+#endif
+/* We use char because int might match the return type of a gcc2
+   builtin and then its argument prototype would still apply.  */
+char FT_New_Memory_Face ();
+int
+main ()
+{
+FT_New_Memory_Face ();
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+         { ac_try='test -s conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ac_cv_lib_freetype_FT_New_Memory_Face=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+ac_cv_lib_freetype_FT_New_Memory_Face=no
+fi
+rm -f conftest.$ac_objext conftest$ac_exeext conftest.$ac_ext
+LIBS=$ac_check_lib_save_LIBS
+fi
+echo "$as_me:$LINENO: result: $ac_cv_lib_freetype_FT_New_Memory_Face" >&5
+echo "${ECHO_T}$ac_cv_lib_freetype_FT_New_Memory_Face" >&6
+if test $ac_cv_lib_freetype_FT_New_Memory_Face = yes; then
+  cat >>confdefs.h <<_ACEOF
+#define HAVE_LIBFREETYPE 1
+_ACEOF
+
+  LIBS="-lfreetype $LIBS"
+
+fi
+
+
 else
 
   echo "$as_me:$LINENO: checking for FT_New_Memory_Face in -lfreetype" >&5
