Move to having libspiro live in its own package   http://libspiro.sf.net/

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -20274,6 +20274,226 @@ _ACEOF
 fi
 
 
+echo "$as_me:$LINENO: checking for TaggedSpiroCPsToBezier in -lspiro" >&5
+echo $ECHO_N "checking for TaggedSpiroCPsToBezier in -lspiro... $ECHO_C" >&6
+if test "${ac_cv_lib_spiro_TaggedSpiroCPsToBezier+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_check_lib_save_LIBS=$LIBS
+LIBS="-lspiro  $LIBS"
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+/* Override any gcc2 internal prototype to avoid an error.  */
+#ifdef __cplusplus
+extern "C"
+#endif
+/* We use char because int might match the return type of a gcc2
+   builtin and then its argument prototype would still apply.  */
+char TaggedSpiroCPsToBezier ();
+int
+main ()
+{
+TaggedSpiroCPsToBezier ();
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+	 { ac_try='test -z "$ac_c_werror_flag"
+			 || test ! -s conftest.err'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; } &&
+	 { ac_try='test -s conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ac_cv_lib_spiro_TaggedSpiroCPsToBezier=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+ac_cv_lib_spiro_TaggedSpiroCPsToBezier=no
+fi
+rm -f conftest.err conftest.$ac_objext \
+      conftest$ac_exeext conftest.$ac_ext
+LIBS=$ac_check_lib_save_LIBS
+fi
+echo "$as_me:$LINENO: result: $ac_cv_lib_spiro_TaggedSpiroCPsToBezier" >&5
+echo "${ECHO_T}$ac_cv_lib_spiro_TaggedSpiroCPsToBezier" >&6
+if test $ac_cv_lib_spiro_TaggedSpiroCPsToBezier = yes; then
+  :
+else
+  cat >>confdefs.h <<\_ACEOF
+#define _NO_LIBSPIRO 1
+_ACEOF
+
+fi
+
+if test "${ac_cv_header_spiroentrypoints_h+set}" = set; then
+  echo "$as_me:$LINENO: checking for spiroentrypoints.h" >&5
+echo $ECHO_N "checking for spiroentrypoints.h... $ECHO_C" >&6
+if test "${ac_cv_header_spiroentrypoints_h+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+fi
+echo "$as_me:$LINENO: result: $ac_cv_header_spiroentrypoints_h" >&5
+echo "${ECHO_T}$ac_cv_header_spiroentrypoints_h" >&6
+else
+  # Is the header compilable?
+echo "$as_me:$LINENO: checking spiroentrypoints.h usability" >&5
+echo $ECHO_N "checking spiroentrypoints.h usability... $ECHO_C" >&6
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+$ac_includes_default
+#include <spiroentrypoints.h>
+_ACEOF
+rm -f conftest.$ac_objext
+if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
+  (eval $ac_compile) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+	 { ac_try='test -z "$ac_c_werror_flag"
+			 || test ! -s conftest.err'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; } &&
+	 { ac_try='test -s conftest.$ac_objext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ac_header_compiler=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+ac_header_compiler=no
+fi
+rm -f conftest.err conftest.$ac_objext conftest.$ac_ext
+echo "$as_me:$LINENO: result: $ac_header_compiler" >&5
+echo "${ECHO_T}$ac_header_compiler" >&6
+
+# Is the header present?
+echo "$as_me:$LINENO: checking spiroentrypoints.h presence" >&5
+echo $ECHO_N "checking spiroentrypoints.h presence... $ECHO_C" >&6
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+#include <spiroentrypoints.h>
+_ACEOF
+if { (eval echo "$as_me:$LINENO: \"$ac_cpp conftest.$ac_ext\"") >&5
+  (eval $ac_cpp conftest.$ac_ext) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } >/dev/null; then
+  if test -s conftest.err; then
+    ac_cpp_err=$ac_c_preproc_warn_flag
+    ac_cpp_err=$ac_cpp_err$ac_c_werror_flag
+  else
+    ac_cpp_err=
+  fi
+else
+  ac_cpp_err=yes
+fi
+if test -z "$ac_cpp_err"; then
+  ac_header_preproc=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+  ac_header_preproc=no
+fi
+rm -f conftest.err conftest.$ac_ext
+echo "$as_me:$LINENO: result: $ac_header_preproc" >&5
+echo "${ECHO_T}$ac_header_preproc" >&6
+
+# So?  What about this header?
+case $ac_header_compiler:$ac_header_preproc:$ac_c_preproc_warn_flag in
+  yes:no: )
+    { echo "$as_me:$LINENO: WARNING: spiroentrypoints.h: accepted by the compiler, rejected by the preprocessor!" >&5
+echo "$as_me: WARNING: spiroentrypoints.h: accepted by the compiler, rejected by the preprocessor!" >&2;}
+    { echo "$as_me:$LINENO: WARNING: spiroentrypoints.h: proceeding with the compiler's result" >&5
+echo "$as_me: WARNING: spiroentrypoints.h: proceeding with the compiler's result" >&2;}
+    ac_header_preproc=yes
+    ;;
+  no:yes:* )
+    { echo "$as_me:$LINENO: WARNING: spiroentrypoints.h: present but cannot be compiled" >&5
+echo "$as_me: WARNING: spiroentrypoints.h: present but cannot be compiled" >&2;}
+    { echo "$as_me:$LINENO: WARNING: spiroentrypoints.h:     check for missing prerequisite headers?" >&5
+echo "$as_me: WARNING: spiroentrypoints.h:     check for missing prerequisite headers?" >&2;}
+    { echo "$as_me:$LINENO: WARNING: spiroentrypoints.h: see the Autoconf documentation" >&5
+echo "$as_me: WARNING: spiroentrypoints.h: see the Autoconf documentation" >&2;}
+    { echo "$as_me:$LINENO: WARNING: spiroentrypoints.h:     section \"Present But Cannot Be Compiled\"" >&5
+echo "$as_me: WARNING: spiroentrypoints.h:     section \"Present But Cannot Be Compiled\"" >&2;}
+    { echo "$as_me:$LINENO: WARNING: spiroentrypoints.h: proceeding with the preprocessor's result" >&5
+echo "$as_me: WARNING: spiroentrypoints.h: proceeding with the preprocessor's result" >&2;}
+    { echo "$as_me:$LINENO: WARNING: spiroentrypoints.h: in the future, the compiler will take precedence" >&5
+echo "$as_me: WARNING: spiroentrypoints.h: in the future, the compiler will take precedence" >&2;}
+    (
+      cat <<\_ASBOX
+## ------------------------------------------ ##
+## Report this to the AC_PACKAGE_NAME lists.  ##
+## ------------------------------------------ ##
+_ASBOX
+    ) |
+      sed "s/^/$as_me: WARNING:     /" >&2
+    ;;
+esac
+echo "$as_me:$LINENO: checking for spiroentrypoints.h" >&5
+echo $ECHO_N "checking for spiroentrypoints.h... $ECHO_C" >&6
+if test "${ac_cv_header_spiroentrypoints_h+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_cv_header_spiroentrypoints_h=$ac_header_preproc
+fi
+echo "$as_me:$LINENO: result: $ac_cv_header_spiroentrypoints_h" >&5
+echo "${ECHO_T}$ac_cv_header_spiroentrypoints_h" >&6
+
+fi
+if test $ac_cv_header_spiroentrypoints_h = yes; then
+  :
+else
+  cat >>confdefs.h <<\_ACEOF
+#define _NO_LIBSPIRO 1
+_ACEOF
+
+fi
+
+
 case "$host" in
 *-pc-cygwin*)
  echo "$as_me:$LINENO: checking for xmlParseFile in -lxml2" >&5
@@ -24281,6 +24501,105 @@ if test $ac_cv_file__usr_X11R6_lib_libtiff_la = yes; then
 else
    STATIC_LIBS="$STATIC_LIBS -ltiff" ; cat >>confdefs.h <<\_ACEOF
 #define _STATIC_LIBTIFF 1
+_ACEOF
+
+fi
+
+fi
+
+fi
+
+fi
+
+
+ fi
+ if test "$ac_cv_lib_spiro_TaggedSpiroCPsToBezier" = "yes"; then
+
+  echo "$as_me:$LINENO: checking for /lib/libspiro.la" >&5
+echo $ECHO_N "checking for /lib/libspiro.la... $ECHO_C" >&6
+if test "${ac_cv_file__lib_libspiro_la+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  test "$cross_compiling" = yes &&
+  { { echo "$as_me:$LINENO: error: cannot check for file existence when cross compiling" >&5
+echo "$as_me: error: cannot check for file existence when cross compiling" >&2;}
+   { (exit 1); exit 1; }; }
+if test -r "/lib/libspiro.la"; then
+  ac_cv_file__lib_libspiro_la=yes
+else
+  ac_cv_file__lib_libspiro_la=no
+fi
+fi
+echo "$as_me:$LINENO: result: $ac_cv_file__lib_libspiro_la" >&5
+echo "${ECHO_T}$ac_cv_file__lib_libspiro_la" >&6
+if test $ac_cv_file__lib_libspiro_la = yes; then
+  :
+else
+
+   echo "$as_me:$LINENO: checking for /usr/lib/libspiro.la" >&5
+echo $ECHO_N "checking for /usr/lib/libspiro.la... $ECHO_C" >&6
+if test "${ac_cv_file__usr_lib_libspiro_la+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  test "$cross_compiling" = yes &&
+  { { echo "$as_me:$LINENO: error: cannot check for file existence when cross compiling" >&5
+echo "$as_me: error: cannot check for file existence when cross compiling" >&2;}
+   { (exit 1); exit 1; }; }
+if test -r "/usr/lib/libspiro.la"; then
+  ac_cv_file__usr_lib_libspiro_la=yes
+else
+  ac_cv_file__usr_lib_libspiro_la=no
+fi
+fi
+echo "$as_me:$LINENO: result: $ac_cv_file__usr_lib_libspiro_la" >&5
+echo "${ECHO_T}$ac_cv_file__usr_lib_libspiro_la" >&6
+if test $ac_cv_file__usr_lib_libspiro_la = yes; then
+  :
+else
+
+    echo "$as_me:$LINENO: checking for /usr/local/lib/libspiro.la" >&5
+echo $ECHO_N "checking for /usr/local/lib/libspiro.la... $ECHO_C" >&6
+if test "${ac_cv_file__usr_local_lib_libspiro_la+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  test "$cross_compiling" = yes &&
+  { { echo "$as_me:$LINENO: error: cannot check for file existence when cross compiling" >&5
+echo "$as_me: error: cannot check for file existence when cross compiling" >&2;}
+   { (exit 1); exit 1; }; }
+if test -r "/usr/local/lib/libspiro.la"; then
+  ac_cv_file__usr_local_lib_libspiro_la=yes
+else
+  ac_cv_file__usr_local_lib_libspiro_la=no
+fi
+fi
+echo "$as_me:$LINENO: result: $ac_cv_file__usr_local_lib_libspiro_la" >&5
+echo "${ECHO_T}$ac_cv_file__usr_local_lib_libspiro_la" >&6
+if test $ac_cv_file__usr_local_lib_libspiro_la = yes; then
+  :
+else
+
+     echo "$as_me:$LINENO: checking for /usr/X11R6/lib/libspiro.la" >&5
+echo $ECHO_N "checking for /usr/X11R6/lib/libspiro.la... $ECHO_C" >&6
+if test "${ac_cv_file__usr_X11R6_lib_libspiro_la+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  test "$cross_compiling" = yes &&
+  { { echo "$as_me:$LINENO: error: cannot check for file existence when cross compiling" >&5
+echo "$as_me: error: cannot check for file existence when cross compiling" >&2;}
+   { (exit 1); exit 1; }; }
+if test -r "/usr/X11R6/lib/libspiro.la"; then
+  ac_cv_file__usr_X11R6_lib_libspiro_la=yes
+else
+  ac_cv_file__usr_X11R6_lib_libspiro_la=no
+fi
+fi
+echo "$as_me:$LINENO: result: $ac_cv_file__usr_X11R6_lib_libspiro_la" >&5
+echo "${ECHO_T}$ac_cv_file__usr_X11R6_lib_libspiro_la" >&6
+if test $ac_cv_file__usr_X11R6_lib_libspiro_la = yes; then
+  :
+else
+   STATIC_LIBS="$STATIC_LIBS -lspiro" ; cat >>confdefs.h <<\_ACEOF
+#define _STATIC_LIBSPIRO 1
 _ACEOF
 
 fi
